//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataProductsEntities : DbContext
    {
        public DataProductsEntities()
            : base("name=DataProductsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatBrand> CatBrands { get; set; }
        public virtual DbSet<CatCatalog> CatCatalogs { get; set; }
        public virtual DbSet<CatColor> CatColors { get; set; }
        public virtual DbSet<CatProvider> CatProviders { get; set; }
        public virtual DbSet<CatRating> CatRatings { get; set; }
        public virtual DbSet<CatSize> CatSizes { get; set; }
        public virtual DbSet<CatTypeDetail> CatTypeDetails { get; set; }
        public virtual DbSet<CatTypeProduct> CatTypeProducts { get; set; }
        public virtual DbSet<ChangesOnProduct> ChangesOnProducts { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DetailProduct> DetailProducts { get; set; }
        public virtual DbSet<HistorialT> HistorialTs { get; set; }
        public virtual DbSet<ImagesProduct> ImagesProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<SimilarProduct> SimilarProducts { get; set; }
        public virtual DbSet<SizeForProduct> SizeForProducts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
